- name: Get all cron file 
  ansible.builtin.find:
    use_regex: true
    file_type: file
    path: "{{ cron_path[ansible_distribution | lower] }}"
    pattern: '^(?!.*({{ initialization_cron.reserve | join("|") }})).*$'
  register: cron

    
- name: Remove cron
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop: "{{ cron.files | json_query('[].path') | flatten }}"
