---
# tasks file for initialization
- name: SSH service settings
  ansible.builtin.import_tasks: ssh.yaml
    
- name: Startup script settings
  ansible.builtin.import_tasks: startup.yaml

- name: User settings
  ansible.builtin.import_tasks: user.yaml

- name: Package management
  ansible.builtin.import_tasks: package.yaml
    
- name: Cron settings
  ansible.builtin.import_tasks: cron.yaml
