- name: Remove packages
  ansible.builtin.package:
    name: '{{ initialization_package.remove }}'
    state: absent
  when: initialization_package.remove is defined

- name: Install packages
  ansible.builtin.package:
    name: '{{ initialization_package.install }}'
    state: present
  register: install
  when: initialization_package.install is defined
  until: install is succeeded
  retries: 3
  delay: 3
  

