- name: Get configure stats of SSH service
  ansible.builtin.stat:
    path: /etc/ssh/sshd_config
  register: sshd_config

- name: Copy configuration of SSH service
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/
    mode: '644'
  when: (not sshd_config.stat.exists) or overwrite.sshd_config
