---
precondition_dependencies:
  wd:
    - python{{ 3 if ansible_python.version.major == 3 else '' }}-psutil

precondition_processes:
  wd:
    - mysql
    - scp
    - node
    - redis
    - nginx

precondition_ports:
  wd:
    - 9001
    - 9010
    - 9020
    - 9030
    - 9040
    - 9050
