---
# vars file for initialization
initialization_startup:
  create: true
  executable: true
  path: /etc/rc.local
  reserve:
    - ^#
    - ^$
    - ^[ ]
    - ^touch
    - route
    - flume
    - elves-agent
    - zabbix
    - mount
  insert:
    - after: '#!'
      content: /sbin/hwclock --systohc

initialization_user:
  delete:
    - 'chenl'
    - 'huangyd'
    - 'tangzc'
    - 'gbit'
    - 'lif'
    - 'asktao'
    - 'apex'
    - 'developer'
    - 'manage'
    - 'mysql'

initialization_package:
  remove:
    - zabbix-agent
  install:
    - gcc
    - lrzsz
    - ftp
    - svn
    - vim
    - sysstat
    - screen
    - enca
    - telnet
    - git
    - rsync
    - autoconf
    - automake
    - unzip
    - zip
    - tmpwatch
    - tcpdump
    - wget
    - zlib*
    - readline-devel
    - sqlite-devel
    - ncurses*
    - libdbi-devel
    - glibc.i686
    - libstdc*
    - dos2unix
    - libstdc++.i686
    - expect
    - libffi-devel
    - libsybdb*
    - openssl*
    - libmnl*
    - ntpd
    - perl-devel
    - libaio
    - libaio-devel
    - perl-Time-HiRes
    - perl-DBD-MySQL
    - bind-utils
    - ftp

initialization_configuration:
  remove:
    - /etc/zabbix
    - /etc/cgrules.conf
    - /usr/local/filebeat-8.3.3
    - /etc/cgconfig.d/cgroup.filebeat.conf
  cron:
    reserve:
      - monitor4
  profile:
    - name: TMOUT
      value: 14400
