---
# vars file for initialization
initialization_startup:
  create: true
  executable: true
  path: /etc/rc.local
  reserve:
    - ^#
    - ^$
    - ^[ ]
    - ^touch
    - route
    - flume
    - elves-agent
    - zabbix
    - mount
  present:
    - after: '#!'
      content: /sbin/hwclock --systohc

initialization_user:
  delete:
    - 'chenl'
    - 'huangyd'
    - 'tangzc'
    - 'gbit'
    - 'lif'
    - 'asktao'
    - 'apex'
    - 'developer'
    - 'manage'
    - 'mysql'

initialization_package:
  remove:
    - zabbix-agent

initalization_configuration:
  remove:
    - /etc/zabbix
    - /etc/cgrules.conf
    - /usr/local/filebeat-8.3.3
    - /etc/cgconfig.d/cgroup.filebeat.conf
  cron:
    reserve:
      - monitor4
