- name: Get pids of processes
  ansible.builtin.pids:
    name: '{{ item }}'
  register: proc
  loop: '{{ precondition_processes[game] }}'

- name: Gather pids
  ansible.builtin.set_fact:
    running_proc_pids: '{{ running_proc_pids | default([]) + item.pids | flatten }}'
  loop: '{{ proc.results }}'
  loop_control:
    label: '{{ item.item }} => {{ item.pids }}'

- name: Verify if there are running process
  ansible.builtin.fail:
    msg: "pids: {{ running_proc_pids | join(', ') }} are running"
  when: running_proc_pids
