- name: Get the pids of whitelist processes
  community.general.pids:
    pattern: '{{ item }}'
  register: whitelist_processes
  loop: '{{ whitelist_process_name }}'

- name: Get the pids of processes
  community.general.pids:
    pattern: '{{ item }}'
  register: processes
  loop: '{{ process_name }}'

- name: Gather pids
  ansible.builtin.set_fact:
    processes_pids: "{{ processes.results | json_query('[].pids') | flatten }}"
    whitelist_pids: "{{ whitelist_processes.results | json_query('[].pids') | flatten }}"

- name: Calc the set difference of processes of pids
  ansible.builtin.set_fact:
    running_processes: '{{ processes_pids | difference(whitelist_pids) }} '

- name: Show processes
  ansible.builtin.debug:
    var: processes.results # , whitelist_processes.results

- name: Show processes
  ansible.builtin.debug:
    var: whitelist_processes.results

- name: Terminate the playbook if needed processes is already deployed
  ansible.builtin.fail:
    msg: 'pids: {{ running_processes | join(", ") }} is running'
  when: running_processes
